# -*- coding: utf-8 -*-
"""ZombieWeaknessNotebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KB2d6HbY5v4rerfSbRLaPhQmoD3wxlul

Zombie Weakness Code

This is the code for my zombie weakness game, that uses lists, inputs, and if else statements.
"""

listweapons = ["Machete", "Glock", "Rock", "Hunting Rifle", "Rocket Launcher", "Gernade"]#Creates a list with a list of weapons to select from
zombieWeakness = listweapons[2]#Selects the second weapon rock in the list as the zombie weakness
print("There is a zombie about to attack you, but you have a moment to pick one of these options. Prepare to fight by picking one of these weapons!" + str(listweapons))#Creates text for the user to read the list of weapons
choice = int(input("Pick an option. You can press 1 to select a given weapon, or press 2 to select your own weapon. "))#Gives the user the option to input their own weapon or select from the list of weapons
if choice == 1: #Creates an if statement, if the user inputs number 1
  userchoicew = input("Pick from the weapons up above 0-5 which weapon you will have: ")#Text to give the user the choice to select the weapons in the given list
  if userchoicew == "2": #If the user chose 2
    print("You have won the fight!")#Will print that they have won the fight
  else:#If another option picked
    print("You have lost the fight!")#If they picked anything other than two, they will get text to tell them that they lost.

if choice == 2:#If the user input 2
  userweapon = input("What is your new weapon? ")#The user will input a weapon of their choice
  if userweapon in listweapons:#If the weapon that the user inputted in the console is the same as one in the list
    userchoicesame = input("Pick from the weapons up above 0-5 which weapon you will have since the weapon you chose was already in the list: ")#Will have the user select from the given list if their weapon is in the list
    if userchoicesame == "2":#If the user selects 2 again
      print("You have won the fight!")#They win the interaction 
    else:#Else, if there is another selection
      print("You have lost the fight!")#They will lose the interaction
  else:#Else
    listweapons.append(userweapon)#The weapon that the user inputted will be added to the list
    print("Your new list is " + str(listweapons))#Will print the new list of weapons
    userinputwithnewweapon = int(input("Please pick out of your new list 0-6 to select a weapon to fight the zombie: "))#Will now have the user select from the new list with their weapon
    if userinputwithnewweapon == 2:#If the user now inputs weapon 2
      print("You have won the battle")#They have won
    else:#Else, if other option picked
      print("You have lost the battle")#The user will lose the battle